<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>NetSearch</PackageId>
    <Title>Search.NET</Title>
    <Authors>Ricardo Peres</Authors>
    <Description>A search proxy for .NET</Description>
    <Copyright>Ricardo Peres</Copyright>
    <PackageProjectUrl>https://github.com/rjperes/NetSearch</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rjperes/NetSearch</RepositoryUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Version="10.0.12" />
  </ItemGroup>

</Project>
